yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug_id>/', views.get_posts, name='group'),
    path('post/<int:post_id>/', views.get_one_post, name='post')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

GENRE_CHOICES = (
    ("R", "Рок"),
    ("E", "Электроника"),
    ("P", "Поп"),
    ("C", "Классика"),
    ("O", "Саундтреки"),
)


class CD(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    artist = models.CharField(max_length=40)
    date = models.DateField()
    genre = models.CharField(max_length=1, choices=GENRE_CHOICES)


class ShowGroup(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(group__gt=0)


class Group(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=150, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True, related_name='posts')

    objects = models.Manager()
    show_group = ShowGroup()


class Event(models.Model):
    name = models.CharField(max_length=200)
    start_at = models.DateTimeField()
    contact = models.EmailField()
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='events')
    location = models.CharField(max_length=400)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from .models import Post, Group
import datetime


def index(request: HttpRequest):
    posts = Post.show_group.all().select_related('author').select_related('group')
    d = Post.objects.filter(text__contains='утро').filter(author_id=2).filter(pub_date__range=(datetime.date(1854, 7, 7), datetime.date(1854, 7, 21)))
    context = {
        'posts': posts,
        'd': d
    }
    return render(request, 'posts/index.html', context=context)


def get_posts(request, slug_id):
    group = get_object_or_404(Group, slug=slug_id)
    posts = Post.objects.filter(group=group).select_related('author').order_by('-pub_date')
    return render(request, 'posts/group_list.html', context={'title': 'Записи сообществ', 'posts': posts, 'group': group})


def get_one_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'title': f'Пост {post.pk}',
        'post': post
    }
    return render(request, 'posts/post.html', context=context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    {% include 'posts/includes/head.html' %}
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <!-- ссылка должна вести на главную страницу -->
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'posts/images/peakpx.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>
    {% block main %} {% endblock %}
    <footer class="border-top text-center py-3">
      <p>© 2023 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
  </body>
</html>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block main %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
          {{ posts }}
          {% for post in posts %}
            <ul>
                <li>
                    <h5>Автор: {{ post.author.get_full_name }}</h5>
                </li>
                <li>
                    <h5>Дата публикации: {{ post.pub_date }}</h5>
                </li>
                <li>
                    <h5>Группа: {{ group }}</h5>
                </li>
            </ul>
          <p>{{ post.text|truncatewords:10 }}</p>
          <p style="text-align: right;"><a href="{% url 'posts:post' post_id=post.pk %}">Смотреть весь пост</a></p>
          {% if not forloop.last %}
          <hr>
          {% endif %}
          {% endfor %}
      </div>
    </main>
{% endblock %}

yatube/templates/posts/includes/head.html
{% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'posts/css/bootstrap.min.css' %}">

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block main %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
          {% for post in posts %}
           <ul>
               <li>
                   Автор: {{ post.author.get_full_name }}
               </li>
               <li>
                   Группа: {{ post.group }}
               </li>
               <li>
                   Дата публикации: {{ post.pub_date }}
               </li>
           </ul>
          <p>{{ post.text|truncatewords:10 }}</p>
          <a href="{% url 'posts:group' slug_id=post.group.slug %}">Все записи группы</a>
          {% if not forloop.last %}
          <hr>
          {% endif %}
          {% endfor %}
      </div>
    </main>
{% endblock %}

yatube/templates/posts/post.html
{% extends 'base.html' %}
{% block main %}
<main>
    <div class="containter py-5">
    <ul>
        <li>
            <h6>Автор: {{ post.author.get_full_name }}</h6>
        </li>
        <li>
            <h6>Группа: {{ post.group }}</h6>
        </li>
        <li>
            <h6>Дата публикации: {{ post.pub_date }}</h6>
        </li>
    </ul>
    </div>
</main>
        <h6>{{ post.text }}</h6>
{% endblock %}